# Type stubs for PyOpenColorIO v2
from typing import Any, List, Optional

class ColorSpace:
    def __init__(self) -> None: ...
    def setName(self, name: str) -> None: ...
    def addAlias(self, alias: str) -> None: ...
    def setFamily(self, family: str) -> None: ...
    def setEncoding(self, encoding: str) -> None: ...
    def setDescription(self, description: str) -> None: ...
    def setBitDepth(self, bit_depth: Any) -> None: ...
    def addCategory(self, category: str) -> None: ...
    def setTransform(self, transform: Any, direction: Any) -> None: ...
    def getName(self) -> str: ...

class GroupTransform:
    def __init__(self) -> None: ...
    def appendTransform(self, transform: Any) -> None: ...

class MatrixTransform:
    def __init__(self) -> None: ...
    def setMatrix(self, matrix: List[float]) -> None: ...

class BuiltinTransform:
    def __init__(self, name: str) -> None: ...
    def setDirection(self, direction: Any) -> None: ...

class Config:
    @staticmethod
    def CreateFromFile(path: str) -> 'Config': ...
    def addColorSpace(self, colorspace: ColorSpace) -> None: ...
    def addDisplayView(self, display: str, view: str, colorspace: str) -> None: ...
    def serialize(self) -> str: ...

# Constants
BIT_DEPTH_F32: Any
TRANSFORM_DIR_FORWARD: Any
COLORSPACE_DIR_FROM_REFERENCE: Any 