# Type stubs for PyOpenColorIO v2
from typing import Any, Iterator, List, overload

# Module-level functions
def GetVersion() -> str: ...
def GetBuiltinTransforms() -> List[str]: ...

class BuiltinTransformRegistry:
    def __init__(self) -> None: ...
    def getBuiltins(self) -> List[tuple[str, str]]: ...

class ColorSpace:
    def __init__(self, referenceSpace: Any = ...) -> None: ...
    def setName(self, name: str) -> None: ...
    def addAlias(self, alias: str) -> None: ...
    def setFamily(self, family: str) -> None: ...
    def setEncoding(self, encoding: str) -> None: ...
    def setDescription(self, description: str) -> None: ...
    def setBitDepth(self, bit_depth: Any) -> None: ...
    def addCategory(self, category: str) -> None: ...
    def setTransform(self, transform: Any, direction: Any) -> None: ...
    def getTransform(self, direction: Any) -> Any: ...
    def getName(self) -> str: ...
    def getDescription(self) -> str: ...
    def getReferenceSpaceType(self) -> Any: ...

class ViewTransform:
    def __init__(self, referenceSpace: Any = ...) -> None: ...
    def setName(self, name: str) -> None: ...
    def getName(self) -> str: ...
    def setDescription(self, description: str) -> None: ...
    def getDescription(self) -> str: ...
    def setTransform(self, transform: Any, direction: Any) -> None: ...
    def getTransform(self, direction: Any) -> Any: ...

class GroupTransform:
    def __init__(self) -> None: ...
    def appendTransform(self, transform: Any) -> None: ...
    def __getitem__(self, index: int) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...

class MatrixTransform:
    def __init__(self) -> None: ...
    def setMatrix(self, matrix: List[float]) -> None: ...
    def getMatrix(self) -> List[float]: ...

class RangeTransform:
    def __init__(self) -> None: ...
    def setMinInValue(self, value: float) -> None: ...
    def setMaxInValue(self, value: float) -> None: ...
    def setMinOutValue(self, value: float) -> None: ...
    def setMaxOutValue(self, value: float) -> None: ...

class ExponentTransform:
    def __init__(self) -> None: ...
    def setValue(self, value: List[float]) -> None: ...

class BuiltinTransform:
    def __init__(self, name: str) -> None: ...
    def setDirection(self, direction: Any) -> None: ...

class FixedFunctionTransform:
    def __init__(
        self, style: Any = ..., params: List[float] = ..., direction: Any = ...
    ) -> None: ...
    def setDirection(self, direction: Any) -> None: ...

class LogCameraTransform:
    def __init__(
        self,
        linSideBreak: List[float] = ...,
        base: float = ...,
        logSideSlope: List[float] = ...,
        logSideOffset: List[float] = ...,
        linSideSlope: List[float] = ...,
        linSideOffset: List[float] = ...,
        linearSlope: List[float] = ...,
        direction: Any = ...,
    ) -> None: ...

class CPUProcessor:
    def applyRGB(self, rgb: Any) -> List[float]: ...

class Processor:
    def getDefaultCPUProcessor(self) -> CPUProcessor: ...

class Config:
    def __init__(self) -> None: ...
    @staticmethod
    def CreateFromFile(path: str) -> "Config": ...
    def addColorSpace(self, colorspace: ColorSpace) -> None: ...
    def addViewTransform(self, viewTransform: ViewTransform) -> None: ...
    def getViewTransform(self, name: str) -> ViewTransform: ...
    @overload
    def addDisplayView(self, display: str, view: str, colorspace: str) -> None: ...
    @overload
    def addDisplayView(
        self,
        *,
        display: str,
        view: str,
        viewTransform: str,
        displayColorSpaceName: str,
    ) -> None: ...
    def getCanonicalName(self, name: str) -> str: ...
    def getMajorVersion(self) -> int: ...
    def getMinorVersion(self) -> int: ...
    def getActiveDisplays(self) -> Iterator[str]: ...
    def setActiveDisplays(self, displays: str) -> None: ...
    def getActiveViews(self) -> Iterator[str]: ...
    def setActiveViews(self, views: str) -> None: ...
    def getDisplays(self) -> Iterator[str]: ...
    def getViews(self, display: str) -> Iterator[str]: ...
    def getDefaultView(self, display: str) -> str: ...
    @overload
    def getProcessor(self, transform: Any) -> Processor: ...
    @overload
    def getProcessor(self, srcName: str, dstName: str) -> Processor: ...
    @overload
    def getProcessor(
        self, srcColorSpaceName: str, display: str, view: str, direction: Any
    ) -> Processor: ...
    def serialize(self) -> str: ...
    def validate(self) -> None: ...

# Constants
BIT_DEPTH_F32: Any
TRANSFORM_DIR_FORWARD: Any
TRANSFORM_DIR_INVERSE: Any
COLORSPACE_DIR_FROM_REFERENCE: Any
VIEWTRANSFORM_DIR_FROM_REFERENCE: Any
ROLE_INTERCHANGE_SCENE: str
ROLE_INTERCHANGE_DISPLAY: str
REFERENCE_SPACE_SCENE: Any
REFERENCE_SPACE_DISPLAY: Any
FIXED_FUNCTION_ACES_RGB_TO_JMH_20: Any
FIXED_FUNCTION_ACES_GAMUT_COMPRESS_20: Any
FIXED_FUNCTION_ACES_OUTPUT_TRANSFORM_20: Any
